version: '3'

services:

  app:
    build:
      context: node
    image: alissonpinto/fullcycle-node
    command: bash -c "npm install && node index.js"
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    networks:
      - fullcycle-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fullcycle-nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - fullcycle-network

  nginx:
    build:
      context: nginx
    image: alissonpinto/fullcycle-nginx
    container_name: nginx
    networks:
      - fullcycle-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  fullcycle-network:
    driver: bridge
